/**
 * INPS office codes ("codice sede") for the F24 INPS section.
 * Source: AdE, "Tabella codici sede INPS" (Strumenti -> Codici per i versamenti), read on 2026-09-21:
 * https://www.agenziaentrate.gov.it/portale/strumenti/codici-attivita-e-tributo/f24-codici-tributo-per-i-versamenti/tabelle-dei-codici-tributo-e-altri-codici-per-il-modello-f24/tabelle-codici-inps-e-enti-previdenziali-ed-assicurativi/tabella-codici-sede-inps
 * Columns: medical checks / artisans and traders / other contributions (the one relevant to Gestione Separata).
 * Codes are 4 digits, zero-padded (the table prints e.g. "100" for Agrigento).
 * Note: the official table lists code 8103 twice ("Torino Nord" and "Torino Sud"); both rows are kept as published.
 */
export interface InpsOffice {
  code: string;
  name: string;
  medicalChecks: boolean;
  artisansTraders: boolean;
  otherContributions: boolean;
}

export const INPS_OFFICES: readonly InpsOffice[] = [
  { code: '0100', name: 'Agrigento', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '0101', name: 'Sciacca', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '0200', name: 'Alessandria', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '0300', name: 'Ancona', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '0391', name: 'Jesi', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { code: '0400', name: 'Aosta', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '0500', name: 'Arezzo', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '0600', name: 'Ascoli Piceno', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '0690', name: 'Fermo', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '0700', name: 'Asti', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '0800', name: 'Avellino', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '0890', name: 'Ariano Irpino', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { code: '0900', name: 'Bari', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '0901', name: 'Andria', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '0993', name: 'Gioia del Colle', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { code: '1000', name: 'Belluno', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '1100', name: 'Benevento', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '1200', name: 'Bergamo', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '1300', name: 'Bologna', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '1301', name: 'Imola', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '1393', name: 'San Lazzaro di Savena', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { code: '1400', name: 'Bolzano', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '1491', name: 'Merano', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { code: '1500', name: 'Brescia', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '1594', name: 'Manerbio', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { code: '1595', name: 'Chiari', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { code: '1600', name: 'Brindisi', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '1700', name: 'Cagliari', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '1701', name: 'Iglesias', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '1791', name: 'Quartu Sant\'Elena', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { code: '1800', name: 'Caltanissetta', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '1900', name: 'Campobasso', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '1990', name: 'Termoli', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { code: '2000', name: 'Caserta', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '2001', name: 'Aversa', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '2100', name: 'Catania', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '2190', name: 'Caltagirone', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '2200', name: 'Catanzaro', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '2201', name: 'Lamezia Terme', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '2202', name: 'Vibo Valenzia', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '2203', name: 'Crotone', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '2300', name: 'Chieti', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '2391', name: 'Vasto', medicalChecks: true, artisansTraders: true, otherContributions: false },
  { code: '2400', name: 'Como', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '2401', name: 'Lecco', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '2490', name: 'Cantù', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { code: '2500', name: 'Cosenza', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '2501', name: 'Rossano Calabro', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '2590', name: 'Paola', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { code: '2591', name: 'Castrovillari', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { code: '2600', name: 'Cremona', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '2700', name: 'Cuneo', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '2791', name: 'Alba C.O', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '2792', name: 'Mondovì', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { code: '2800', name: 'Enna', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '2900', name: 'Ferrara', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '3000', name: 'Firenze', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '3001', name: 'Prato', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '3090', name: 'Empoli C.O', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '3093', name: 'Scandicci', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { code: '3094', name: 'Sesto Fiorentino', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { code: '3100', name: 'Foggia', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '3191', name: 'San Severo', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { code: '3200', name: 'Forli\'', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '3201', name: 'Rimini', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '3290', name: 'Cesena C.O.', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '3300', name: 'Frosinone', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '3301', name: 'Cassino', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '3400', name: 'Genova', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '3401', name: 'Sestri Levante', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '3402', name: 'Sestri Ponente', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '3500', name: 'Gorizia', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '3600', name: 'Grosseto', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '3700', name: 'Imperia', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '3800', name: 'L\'Aquila', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '3801', name: 'Sulmona', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '3802', name: 'Avezzano', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '3900', name: 'La Spezia', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '4000', name: 'Latina', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '4091', name: 'Terracina', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { code: '4100', name: 'Lecce', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '4101', name: 'Casarano', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '4190', name: 'Nardò', medicalChecks: true, artisansTraders: true, otherContributions: false },
  { code: '4200', name: 'Livorno', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '4201', name: 'Piombino', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '4300', name: 'Lucca', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '4400', name: 'Macerata', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '4500', name: 'Mantova', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '4600', name: 'Massa Carrara', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '4700', name: 'Matera', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '4800', name: 'Messina', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '4891', name: 'Santa Teresa di Riva', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { code: '4892', name: 'Barcellona Pozzo di Gotto', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { code: '4894', name: 'Milazzo', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '4900', name: 'Milano', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '4901', name: 'Monza', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '4902', name: 'Milano Nord', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '4903', name: 'Milano Missori', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '4904', name: 'Milano Fiori', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '4905', name: 'Milano Corvetto', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '4908', name: 'Milano Legnano', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '4909', name: 'Milano Seregno (C.O.)', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '4927', name: 'Lodi', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '4955', name: 'Sesto San Giovanni', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '4979', name: 'Vimercate', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { code: '4991', name: 'Melegnano', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { code: '4995', name: 'Desio (C.O.)', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '5000', name: 'Modena', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '5094', name: 'Sassuolo', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { code: '5100', name: 'Napoli', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '5101', name: 'Castellammare di Stabia', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '5102', name: 'Nola', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '5103', name: 'Napoli Arzano', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '5104', name: 'Napoli Soccavo', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '5105', name: 'Napoli Vomero', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '5106', name: 'Pozzuoli', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '5199', name: 'Giugliano', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { code: '5200', name: 'Novara', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '5290', name: 'V.C.O. - Verbano Cusio Ossola', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '5300', name: 'Nuoro', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '5400', name: 'Padova', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '5490', name: 'Cittadella', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { code: '5500', name: 'Palermo', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '5502', name: 'Palermo Sud Ovest', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '5503', name: 'Carini', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '5593', name: 'Bagheria', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '5600', name: 'Parma', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '5700', name: 'Pavia', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '5791', name: 'Vigevano', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { code: '5800', name: 'Perugia', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '5801', name: 'Citta\' di Castello', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '5890', name: 'Foligno', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { code: '5900', name: 'Pesaro', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '5992', name: 'Fano', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { code: '6000', name: 'Pescara', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '6100', name: 'Piacenza', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '6200', name: 'Pisa', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '6300', name: 'Pistoia', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '6400', name: 'Potenza', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '6490', name: 'Melfi', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { code: '6500', name: 'Ragusa', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '6590', name: 'Modica', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { code: '6600', name: 'Ravenna', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '6691', name: 'Lugo', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { code: '6700', name: 'Reggio Calabria', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '6790', name: 'Palmi', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { code: '6791', name: 'Locri', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { code: '6800', name: 'Reggio Emilia', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '6891', name: 'Guastalla', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { code: '6900', name: 'Rieti', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '7000', name: 'Roma', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '7001', name: 'Roma Eur', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '7002', name: 'Roma Monteverde', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '7003', name: 'Roma Ostia Lido', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '7004', name: 'Roma Montesacro', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '7005', name: 'Roma Centro', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '7006', name: 'Civitavecchia', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '7009', name: 'Roma Casilino Prenestino', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '7010', name: 'Roma Tuscolano', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '7012', name: 'Roma Aurelio', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '7013', name: 'Roma Tiburtino', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '7014', name: 'Roma Flaminio', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '7015', name: 'Pomezia', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '7074', name: 'Grottaferrata', medicalChecks: true, artisansTraders: true, otherContributions: false },
  { code: '7091', name: 'Tivoli', medicalChecks: true, artisansTraders: true, otherContributions: false },
  { code: '7092', name: 'Velletri', medicalChecks: true, artisansTraders: true, otherContributions: false },
  { code: '7094', name: 'Monterotondo', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { code: '7095', name: 'Anzio', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { code: '7096', name: 'Palestrina', medicalChecks: true, artisansTraders: true, otherContributions: false },
  { code: '7099', name: 'Guidonia', medicalChecks: true, artisansTraders: true, otherContributions: false },
  { code: '7100', name: 'Rovigo', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '7200', name: 'Salerno', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '7201', name: 'Nocera Inferiore', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '7202', name: 'Battipaglia', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '7300', name: 'Sassari', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '7390', name: 'Olbia', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { code: '7400', name: 'Savona', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '7500', name: 'Siena', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '7600', name: 'Siracusa', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '7601', name: 'Noto', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '7700', name: 'Sondrio', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '7800', name: 'Taranto', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '7890', name: 'Manduria', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { code: '7900', name: 'Teramo', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '8000', name: 'Terni', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '8100', name: 'Torino', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '8101', name: 'Moncalieri', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '8102', name: 'Ivrea', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '8103', name: 'Torino Nord', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '8103', name: 'Torino Sud', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '8105', name: 'Pinerolo', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '8106', name: 'Collegno', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '8110', name: 'Torino Lingotto', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '8191', name: 'Orbassano', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { code: '8192', name: 'Chieri', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { code: '8193', name: 'Chivasso', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { code: '8200', name: 'Trapani', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '8290', name: 'Marsala', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '8300', name: 'Trento', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '8400', name: 'Treviso', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '8490', name: 'Conegliano C.O.', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '8500', name: 'Trieste', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '8600', name: 'Udine', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '8691', name: 'Cervignano del Friuli', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { code: '8700', name: 'Varese', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '8790', name: 'Busto Arsizio C.O.', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '8800', name: 'Venezia', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '8801', name: 'San Dona\' di Piave', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '8891', name: 'Chioggia', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { code: '8900', name: 'Vercelli', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '8901', name: 'Biella', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '9000', name: 'Verona', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '9090', name: 'Legnago', medicalChecks: true, artisansTraders: false, otherContributions: false },
  { code: '9100', name: 'Vicenza', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '9200', name: 'Viterbo', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '9300', name: 'Pordenone', medicalChecks: true, artisansTraders: true, otherContributions: true },
  { code: '9400', name: 'Isernia', medicalChecks: true, artisansTraders: true, otherContributions: true },
];

export function findInpsOffice(code: string): InpsOffice | undefined {
  return INPS_OFFICES.find((o) => o.code === code.padStart(4, '0'));
}

/** All rows for a code (the official table can list the same code more than once). */
export function findInpsOffices(code: string): InpsOffice[] {
  return INPS_OFFICES.filter((o) => o.code === code.padStart(4, '0'));
}

/** True when the code exists and accepts "other contributions" (Gestione Separata). */
export function isValidInpsOfficeForGestioneSeparata(code: string): boolean {
  return findInpsOffice(code)?.otherContributions === true;
}
